version: "3"
services:
  mongodb_service:
    image: mongo:4.4.2-bionic
    container_name: mongodb--dev
    environment:
      MONGO_LOG_DIR: /dev/null
    volumes:
      - near-vbi-backend-mongodb-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - dev-network
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

networks:
  dev-network:

volumes:
  near-vbi-backend-mongodb-volume:
    driver: local
